# Generated by Django 5.0.6 on 2024-06-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_login_model',
        ),
    ]
