# Generated by Django 5.0.6 on 2024-06-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_event_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_model',
        ),
    ]
