# Generated by Django 5.0.6 on 2024-06-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_venue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venue',
            new_name='Venue_event',
        ),
    ]
