# Generated by Django 5.0.6 on 2024-06-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_rename_venue_venue_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventapp.venue_event'),
            preserve_default=False,
        ),
    ]
