# Generated by Django 5.0.6 on 2024-06-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
