# Generated by Django 5.0.6 on 2024-06-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0016_venue_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(default=1, upload_to='venue_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.venue_event'),
        ),
    ]
