# Generated by Django 5.0.6 on 2024-06-27 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0017_venue_image_venue_location_alter_booking_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.venue'),
        ),
    ]
