# Generated by Django 5.0.6 on 2024-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0020_foodpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpackage',
            name='image',
            field=models.ImageField(default=1, upload_to='food_packages/'),
            preserve_default=False,
        ),
    ]
