# Generated by Django 5.0.6 on 2024-06-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0021_foodpackage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpackage',
            name='image',
        ),
    ]
