# Generated by Django 5.0.6 on 2024-06-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0023_vendor_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
