# Generated by Django 5.0.6 on 2024-07-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0027_booking_model_my'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_model_my',
            name='title',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.DeleteModel(
            name='Booking_model_my',
        ),
    ]
