# Generated by Django 5.0.6 on 2024-07-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0028_remove_booking_model_my_title_delete_attendee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall_last_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
