# Generated by Django 5.0.6 on 2024-07-15 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0029_hall_last_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_last_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.hall_last_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.user')),
            ],
        ),
    ]
