# Generated by Django 5.0.6 on 2024-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0031_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpackage',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
