# Generated by Django 5.0.6 on 2024-07-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0033_alter_foodpackage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodpackage',
            old_name='image',
            new_name='food_image',
        ),
    ]
