# Generated by Django 5.0.6 on 2024-07-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0034_rename_image_foodpackage_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpackage',
            name='food_image',
        ),
    ]
