# Generated by Django 5.0.6 on 2024-07-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0036_foodpackage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_model_one',
        ),
    ]
